{% set name = "types-freezegun" %}
{% set version = "1.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-freezegun-{{ version }}.tar.gz
  sha256: 6f05108d468baecadf999873bd37e57b25ceb35d35d3f83e7a742f25d6fe8b0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/freezegun-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for freezegun
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
