{% set name = "types-freezegun" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-freezegun-{{ version }}.tar.gz
  sha256: 45f5f3e75546fbe05da2f19f769b2feb22f14c304f47f3f7ecbad633688302a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/freezegun-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for freezegun
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
